// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/28/2026, 8:18:33 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/plugins/**/*.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/composables/**/*.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/utils/**/*.{js,ts,mjs}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mdreesen/Documents/Programming/projects/ghostformInfo/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;